# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Adventures in a Software World
header-img: img/hands-bg.jpg
email: jonathon.sturdevant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I been working in the software world for over a decade and have run across
  numerous things that have amazed me. In an effort to share how I see the
  world, this blog has been created.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jsturdevant.github.io" # the base hostname & protocol for your site
twitter_username: jonno0211
github_username:  jsturdevant
facebook_username:  jonathon.sturdevant
linkedin_username: jsturdevant
bitbucket_username: jsturdevant

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "jon"
      header-img: "img/config-bg.jpg"
